<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, provide, reactive, ref } from 'vue'
import BottomNav from './components/BottomNav.vue'
import SectionList from './components/SectionList.vue'
import QrScanner from 'qr-scanner'

const view = ref('landing'), authMode = ref('login'), busy = ref(false), toastText = ref('')
const auth = reactive({ username:'', password:'', error:'' })
const bind = reactive({ open:false, code:'', error:'', scanning:false, scanStatus:'将屏幕二维码完整放入取景框' })
const annotationText = ref(''), formError = ref(''), video = ref(null), canvas = ref(null)
const qrVideo = ref(null)
const coverInput = ref(null)
const enrollment = reactive({ file:null, preview:'', title:'', error:'', uploading:false, created:null })
const state = reactive({ capabilities:[], user:null, devices:[], comments:[], feedback:[], inspirations:[], reviewQueue:[], readingSession:null, vision:null, activeComment:null, activeReview:null, annotationReturn:'home', cameraStream:null, cameraStatus:'摄像头尚未启动' })
provide('isAdmin', computed(() => state.user?.role === 'admin'))
let pollTimer, deviceTimer, cameraTimer, uploading = false
let qrScanner = null
const apiBase = location.pathname.startsWith('/living-margins/') ? '/living-margins' : ''

async function api(path, options={}) { const response=await fetch(`${apiBase}${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options}); const body=await response.json().catch(()=>({error:'服务返回了无效内容'})); if(!response.ok) throw new Error(body.error||'请求失败'); return body }
function notify(text){ toastText.value=text; clearTimeout(notify.timer); notify.timer=setTimeout(()=>toastText.value='',2400) }
function applyBootstrap(body){ state.capabilities=body.capabilities||[]; state.user=body.user; state.devices=body.devices||[]; state.comments=body.comments||[]; state.feedback=body.feedback||[]; state.inspirations=body.inspirations||[]; state.reviewQueue=body.review_queue||[]; state.readingSession=body.reading_session; state.vision=body.vision }
async function bootstrap(){ try{ applyBootstrap(await api('/api/bootstrap')); view.value='home'; await claimPairing(); startDevicePolling() }catch{ view.value='landing' } }
async function refresh(){ try{ applyBootstrap(await api('/api/bootstrap')) }catch{} }
function startDevicePolling(){ stopDevicePolling(); if(state.capabilities.includes('device_presence')) deviceTimer=setInterval(refresh,5000) }
function stopDevicePolling(){ clearInterval(deviceTimer); deviceTimer=null }
function startPolling(){ stopPolling(); refresh(); pollTimer=setInterval(refresh,1200) }
function stopPolling(){ clearInterval(pollTimer); pollTimer=null }
async function claimPairing(){ const token=new URLSearchParams(location.search).get('pair'); if(!token||!state.capabilities.includes('qr_pairing'))return; try{await api('/api/devices/pair/claim',{method:'POST',body:JSON.stringify({pairing_token:token})}); history.replaceState({},'',location.pathname); await refresh(); notify('屏幕绑定成功')}catch(e){history.replaceState({},'',location.pathname);notify(e.message)} }

const snapshot = computed(()=> state.readingSession?.status==='paused' ? {...state.vision,book_id:state.readingSession.book_id||state.vision?.book_id,title:state.readingSession.book_title||state.vision?.title,pages:state.readingSession.pages||state.vision?.pages,status:'paused'} : state.vision)
const pageText = computed(()=> snapshot.value?.pages?.length===2 ? `${snapshot.value.pages[0]} — ${snapshot.value.pages[1]}` : '—')
const currentComment = computed(()=>snapshot.value?.comment)
const feedbackAction = computed(()=>state.feedback.find(i=>i.comment_id===String(currentComment.value?.id))?.action)
const recognitionText = computed(()=> state.readingSession?.status==='paused'?'阅读已暂停':({waiting_camera:'等待相机',searching_book:'正在识别书目',searching_page:'正在寻找页码',recognizing:'正在识别页码',stable:'识别稳定',turning:'检测到翻页',frame_unstable:'画面需要调整'}[snapshot.value?.status]||'尚未开始识别'))
const activePages = computed(()=>{const source=state.readingSession?.status==='paused'?state.readingSession:state.vision; return source?.pages?.length===2?`${source.pages[0]} — ${source.pages[1]}`:'—'})
const canMark = computed(()=>state.capabilities.includes('inspirations')&&state.readingSession?.status==='active'&&state.vision?.book_id&&state.vision?.pages?.length===2)
const agreed = computed(()=>state.feedback.filter(i=>i.action==='agree'))

async function submitAuth(){ auth.error=''; busy.value=true; try{await api(`/api/auth/${authMode.value}`,{method:'POST',body:JSON.stringify({username:auth.username,password:auth.password})}); await bootstrap()}catch(e){auth.error=e.message}finally{busy.value=false} }
async function logout(){stopCamera();stopPolling();stopDevicePolling();await api('/api/auth/logout',{method:'POST',body:'{}'});Object.assign(state,{capabilities:[],user:null,devices:[],comments:[],feedback:[],inspirations:[],reviewQueue:[],readingSession:null,vision:null});view.value='landing'}
async function bindDevice(){bind.error='';try{await api('/api/devices/bind',{method:'POST',body:JSON.stringify({machine_code:bind.code})});bind.open=false;bind.code='';await refresh();notify('屏幕绑定成功')}catch(e){bind.error=e.message}}
async function startQrScan(){ bind.error=''; bind.scanning=true; bind.scanStatus='正在启动相机…'; await nextTick(); try{ qrScanner=new QrScanner(qrVideo.value,result=>handleQrResult(result.data),{preferredCamera:'environment',highlightScanRegion:true,highlightCodeOutline:true,returnDetailedScanResult:true,maxScansPerSecond:8}); await qrScanner.start(); bind.scanStatus='将屏幕二维码完整放入取景框' }catch(e){ stopQrScan(); bind.error=e.name==='NotAllowedError'?'未获得相机权限，请在浏览器设置中允许':'无法启动扫码相机，请改用机器码绑定' } }
function stopQrScan(){ qrScanner?.stop(); qrScanner?.destroy(); qrScanner=null; bind.scanning=false }
function closeBind(){ stopQrScan(); bind.open=false; bind.error='' }
async function handleQrResult(raw){ if(!raw)return; stopQrScan(); bind.scanStatus='已识别，正在绑定…'; try{ let token='',machineCode=''; try{const url=new URL(raw,location.href);token=url.searchParams.get('pair')||url.searchParams.get('pairing_token')||'';machineCode=url.searchParams.get('machine_code')||''}catch{} if(!token&&!machineCode){if(/^LM-[A-Z0-9-]+$/i.test(raw.trim()))machineCode=raw.trim();else token=raw.trim()} if(token)await api('/api/devices/pair/claim',{method:'POST',body:JSON.stringify({pairing_token:token})});else await api('/api/devices/bind',{method:'POST',body:JSON.stringify({machine_code:machineCode})});bind.open=false;bind.code='';await refresh();notify('二维码识别成功，屏幕已绑定')}catch(e){bind.error=e.message;bind.scanStatus='绑定失败，请重新扫描';bind.scanning=true;await nextTick();startQrScan()} }
async function navigate(target){ if(target==='reading'){await enterReading();return} leaveReading();view.value=target }
function selectCover(event){const file=event.target.files?.[0];if(!file)return;if(enrollment.preview)URL.revokeObjectURL(enrollment.preview);enrollment.file=file;enrollment.preview=URL.createObjectURL(file);enrollment.title=file.name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').trim();enrollment.error='';enrollment.created=null}
async function coverJpeg(){const bitmap=await createImageBitmap(enrollment.file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const output=document.createElement('canvas');output.width=Math.round(bitmap.width*scale);output.height=Math.round(bitmap.height*scale);output.getContext('2d',{alpha:false}).drawImage(bitmap,0,0,output.width,output.height);bitmap.close();return await new Promise((resolve,reject)=>output.toBlob(blob=>blob?resolve(blob):reject(new Error('无法处理封面图片')),'image/jpeg',.9))}
async function uploadBook(){if(state.user?.role!=='admin')return;enrollment.error='';if(!enrollment.file){enrollment.error='请先拍摄或选择封面';return}if(!enrollment.title.trim()){enrollment.error='请填写书名';return}enrollment.uploading=true;try{const jpeg=await coverJpeg();const response=await fetch(`${apiBase}/api/admin/books`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'image/jpeg','X-Book-Title':encodeURIComponent(enrollment.title.trim())},body:jpeg});const body=await response.json().catch(()=>({error:'服务返回了无效内容'}));if(!response.ok)throw new Error(body.error||'录入失败');enrollment.created=body.book;notify(`《${body.book.title}》已录入书库`)}catch(e){enrollment.error=e.message}finally{enrollment.uploading=false}}
function resetEnrollment(){if(enrollment.preview)URL.revokeObjectURL(enrollment.preview);Object.assign(enrollment,{file:null,preview:'',title:'',error:'',uploading:false,created:null});if(coverInput.value)coverInput.value.value=''}
async function enterReading(){try{if(!state.readingSession){const body=await api('/api/reading/start',{method:'POST',body:JSON.stringify({device_id:state.devices[0]?.id??null})});state.readingSession=body.reading_session}view.value='reading';startPolling();await nextTick();await startCamera()}catch(e){notify(e.message)}}
function leaveReading(){stopCamera();stopPolling();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});screen.orientation?.unlock?.()}
async function pauseReading(){try{const action=state.readingSession?.status==='paused'?'resume':'pause';const body=await api(`/api/reading/${action}`,{method:'POST',body:'{}'});state.readingSession=body.reading_session;if(action==='pause')openAnnotation(null,'reading')}catch(e){notify(e.message)}}
async function endReading(){try{await api('/api/reading/end',{method:'POST',body:'{}'});state.readingSession=null;leaveReading();view.value='home';notify('本次阅读已经结束')}catch(e){notify(e.message)}}
async function markInspiration(){try{const body=await api('/api/inspirations/mark',{method:'POST',body:'{}'});const i=state.inspirations.findIndex(x=>x.id===body.inspiration.id);i<0?state.inspirations.unshift(body.inspiration):state.inspirations.splice(i,1,body.inspiration);notify(body.created?'已加入灵感集':'这一页已经在灵感集中')}catch(e){notify(e.message)}}
async function sendFeedback(action){if(!currentComment.value)return;try{const body=await api('/api/feedback',{method:'POST',body:JSON.stringify({comment_id:currentComment.value.id,action})});const i=state.feedback.findIndex(x=>x.comment_id===body.feedback.comment_id);i<0?state.feedback.unshift(body.feedback):state.feedback.splice(i,1,body.feedback);notify(action==='agree'?'已赞同这条批注':'已记录不赞同')}catch(e){notify(e.message)}}

function openAnnotation(comment=null, returnView='profile'){state.annotationReturn=returnView;state.activeComment=comment?{...comment}:{id:null,book_id:state.readingSession?.book_id,book_title:state.readingSession?.book_title,pages:state.readingSession?.pages,body:'',status:'draft'};annotationText.value=state.activeComment.body||'';formError.value='';stopPolling();view.value='annotation'}
async function saveDraft(){const body=await api('/api/comments/draft',{method:'POST',body:JSON.stringify({comment_id:state.activeComment?.id??null,body:annotationText.value})});state.activeComment=body.comment;const i=state.comments.findIndex(x=>x.id===body.comment.id);i<0?state.comments.unshift(body.comment):state.comments.splice(i,1,body.comment);return body.comment}
async function saveOnly(){try{await saveDraft();notify('草稿已保存')}catch(e){formError.value=e.message}}
async function submitComment(){formError.value='';try{const draft=await saveDraft();const body=await api('/api/comments/submit',{method:'POST',body:JSON.stringify({comment_id:draft.id,body:annotationText.value})});const i=state.comments.findIndex(x=>x.id===body.comment.id);state.comments.splice(i,1,body.comment);notify('批注已提交审核');await closeAnnotation()}catch(e){formError.value=e.message}}
async function closeAnnotation(){if(state.annotationReturn==='reading'&&state.readingSession?.status==='paused'){const body=await api('/api/reading/resume',{method:'POST',body:'{}'});state.readingSession=body.reading_session;await enterReading()}else view.value=state.annotationReturn}
async function convertInspiration(item){try{const body=await api('/api/inspirations/convert',{method:'POST',body:JSON.stringify({inspiration_id:item.id})});state.inspirations=state.inspirations.filter(x=>x.id!==item.id);openAnnotation(body.comment,'profile')}catch(e){notify(e.message)}}
function openReview(comment){state.activeReview={...comment};formError.value='';view.value='review'}
async function review(decision){try{const body=await api('/api/admin/comments/review',{method:'POST',body:JSON.stringify({comment_id:state.activeReview.id,decision})});state.reviewQueue=state.reviewQueue.filter(x=>x.id!==body.comment.id);view.value='profile';notify(decision==='approved'?'批注已批准并发布':'批注已拒绝')}catch(e){formError.value=e.message}}

function devicePresence(d){return !d?.online?'离线':d.connection_mode==='realtime'?'实时在线':'轮询在线'}
function formatSeen(ts){if(!ts)return'尚未连接';const s=Math.max(0,Math.round(Date.now()/1000-ts));return s<5?'刚刚连接':s<60?`${s} 秒前连接`:s<3600?`${Math.floor(s/60)} 分钟前连接`:new Date(ts*1000).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function pages(item){return item?.pages?.length===2?`P${item.pages[0]}–${item.pages[1]}`:'页码未知'}
function statusText(s){return {draft:'草稿',pending:'待审核',approved:'已通过',rejected:'未通过'}[s]||s}

async function startCamera(){if(state.cameraStream||!navigator.mediaDevices?.getUserMedia)return;try{state.cameraStatus='正在请求摄像头权限…';state.cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.value.srcObject=state.cameraStream;await video.value.play();state.cameraStatus='摄像头已启动 · 正在上传';await uploadFrame();cameraTimer=setInterval(uploadFrame,1200)}catch(e){stopCamera();state.cameraStatus=e.name==='NotAllowedError'?'未获得摄像头权限，请在浏览器设置中允许':`无法启动摄像头：${e.message}`}}
function stopCamera(){clearInterval(cameraTimer);cameraTimer=null;state.cameraStream?.getTracks().forEach(t=>t.stop());state.cameraStream=null;if(video.value)video.value.srcObject=null;state.cameraStatus='摄像头尚未启动'}
async function uploadFrame(){if(!state.cameraStream||uploading||state.readingSession?.status!=='active'||video.value?.readyState<2)return;const width=Math.min(video.value.videoWidth,1280),height=Math.round(video.value.videoHeight*width/video.value.videoWidth);canvas.value.width=width;canvas.value.height=height;canvas.value.getContext('2d',{alpha:false}).drawImage(video.value,0,0,width,height);uploading=true;try{const blob=await new Promise(r=>canvas.value.toBlob(r,'image/jpeg',.72));const response=await fetch(`${apiBase}/api/vision/frame`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'image/jpeg'},body:blob});if(!response.ok)throw new Error('画面上传失败');state.cameraStatus='画面已送达云端 · 持续识别中'}catch(e){state.cameraStatus=e.message}finally{uploading=false}}
onMounted(bootstrap);onBeforeUnmount(()=>{stopCamera();stopQrScan();stopPolling();stopDevicePolling();if(enrollment.preview)URL.revokeObjectURL(enrollment.preview)})
</script>

<template>
<main class="site-shell">
  <section v-if="view==='landing'" class="landing page"><header class="top-nav"><button class="wordmark"><strong>众生行记</strong><span>LIVING MARGINS</span></button><nav><button @click="authMode='login';view='auth'">登录</button><button class="button primary small" @click="authMode='register';view='auth'">开始使用</button></nav></header><div class="hero"><div class="orb mint"></div><p class="eyebrow">PHYSICAL BOOKS / LIVING NOTES</p><h1>让每一页，<br>遇见读过它的人。</h1><p>专注读手中的书。页码由手机安静识别，来自其他读者的批注会在身旁自然出现。</p><div class="actions"><button class="button primary" @click="authMode='register';view='auth'">开始使用</button><button class="button outline" @click="$refs.story.scrollIntoView({behavior:'smooth'})">了解如何工作</button></div></div><div ref="story" class="story"><article v-for="(item,i) in [['架起手机','进入阅读后自动打开横屏取景，让整本书留在画面中。'],['翻动纸页','云端识别封面和页码，书名与进度同步到你的页边屏幕。'],['留下页边','记录灵感、发表批注，也回应曾在同一页停留的人。']]" :key="item[0]"><span>0{{i+1}}</span><h2>{{item[0]}}</h2><p>{{item[1]}}</p></article></div><footer class="marketing-footer"><strong>众生行记</strong><span>为纸页保留一点活着的边缘。</span></footer></section>

  <section v-else-if="view==='auth'" class="auth-page page"><header class="simple-header"><button @click="view='landing'">← 返回首页</button><span>ACCOUNT</span></header><div class="auth-grid"><div><p class="eyebrow">YOUR READING MARGIN</p><h1>回到你的<br>阅读现场。</h1><p>登录后继续阅读、查看批注与灵感。</p></div><form class="panel" @submit.prevent="submitAuth"><div class="tabs"><button type="button" :class="{active:authMode==='login'}" @click="authMode='login'">登录</button><button type="button" :class="{active:authMode==='register'}" @click="authMode='register'">创建账号</button></div><label>用户名<input v-model="auth.username" minlength="2" maxlength="24" autocomplete="username" required></label><label>密码<input v-model="auth.password" type="password" minlength="6" required></label><p class="error">{{auth.error}}</p><button class="button primary wide" :disabled="busy">{{busy?'请稍候…':authMode==='login'?'进入众生行记':'创建并进入'}}</button><small>登录状态会安全地保留在这台设备上。</small></form></div></section>

  <section v-else-if="view==='home'" class="app-page"><header class="app-title"><div><span class="eyebrow">TODAY'S MARGIN</span><h1>众生行记</h1></div><span>{{state.user?.username}}</span></header><div class="app-content"><section class="reading-card"><div class="orb peach"></div><header><div><span class="label">当前书目</span><h2>{{snapshot?.title||state.readingSession?.book_title||'尚未识别书籍'}}</h2></div><button class="reading-entry" @click="enterReading"><span>{{state.readingSession?'继续阅读':'开始阅读'}}</span><strong>进入取景 →</strong></button></header><div class="reading-stats"><div><span>识别状态</span><strong>{{recognitionText}}</strong><p>{{snapshot?.status==='stable'?'书目与页码均已确认。':'保持书页完整、稳定地处于取景范围内。'}}</p></div><div><span>当前页码</span><strong>{{pageText}}</strong></div></div><article class="comment-preview"><header><span>随机批注</span><span>{{currentComment?`P${currentComment.page}`:'等待页码'}}</span></header><blockquote>{{currentComment?.text||'识别到当前书页后，其他读者留下的批注会出现在这里。'}}</blockquote><p>{{currentComment?`来自 ${currentComment.author||'匿名读者'}`:'—'}}</p></article><footer><button :class="{selected:feedbackAction==='agree'}" :disabled="!currentComment" @click="sendFeedback('agree')">赞同</button><button :class="{selected:feedbackAction==='disagree'}" :disabled="!currentComment" @click="sendFeedback('disagree')">不赞同</button><button :disabled="!canMark" @click="markInspiration">加入灵感集</button></footer></section><SectionList index="01" title="页边屏幕"><template #action><button class="text-link" @click="bind.open=true">绑定新屏幕</button></template><div v-if="!state.devices.length" class="empty">—　还没有绑定屏幕。</div><article v-for="(d,i) in state.devices" :key="d.id" class="record"><span>0{{i+1}}</span><div><strong>{{d.name}}</strong><small>{{d.machine_code}} · {{formatSeen(d.last_seen_at)}}</small></div><em>{{devicePresence(d)}}</em></article></SectionList></div><BottomNav active="home" @navigate="navigate"/></section>

  <section v-else-if="view==='profile'" class="app-page"><header class="app-title"><div><span class="eyebrow">PERSONAL MARGIN</span><h1>我的页边</h1></div><button @click="logout">退出登录</button></header><div class="app-content profile-content"><section class="profile-intro"><div>{{state.user?.username?.slice(0,1)}}</div><h2>{{state.user?.username}}</h2><p>你的批注、回应与阅读灵感，都安静地收在这里。</p></section><SectionList index="01" title="我的批注" :meta="`${state.comments.length} 条记录`"><div v-if="!state.comments.length" class="empty">—　还没有批注。</div><button v-for="(c,i) in state.comments" :key="c.id" class="record interactive" @click="openAnnotation(c)"><span>{{String(i+1).padStart(2,'0')}}</span><div><strong>{{c.body||'尚未填写内容'}}</strong><small>{{c.book_title||'未命名书籍'}} · {{pages(c)}}</small></div><em>{{statusText(c.status)}}</em></button></SectionList><SectionList index="02" title="灵感集" :meta="`${state.inspirations.length} 条记录`"><div v-if="!state.inspirations.length" class="empty">—　阅读中标记的灵感会留在这里。</div><button v-for="(item,i) in state.inspirations" :key="item.id" class="record interactive" @click="convertInspiration(item)"><span>{{String(i+1).padStart(2,'0')}}</span><div><strong>{{item.book_title||'未命名书籍'}}</strong><small>{{pages(item)}} · 点击补写批注</small></div><em>待补写</em></button></SectionList><SectionList index="03" title="赞同的批注" :meta="`${agreed.length} 条记录`"><div v-if="!agreed.length" class="empty">—　还没有赞同过的批注。</div><article v-for="(item,i) in agreed" :key="item.comment_id" class="record"><span>{{String(i+1).padStart(2,'0')}}</span><div><strong>{{item.book_id||'阅读批注'}}</strong><small>{{item.page?`P${item.page}`:'页码未知'}}</small></div><em>已赞同</em></article></SectionList><SectionList v-if="state.user?.role==='admin'" index="04" title="审核队列" :meta="`${state.reviewQueue.length} 条待审`"><div v-if="!state.reviewQueue.length" class="empty">—　当前没有等待审核的批注。</div><button v-for="(c,i) in state.reviewQueue" :key="c.id" class="record interactive" @click="openReview(c)"><span>{{String(i+1).padStart(2,'0')}}</span><div><strong>{{c.body}}</strong><small>{{c.book_title}} · {{pages(c)}} · {{c.author_username}}</small></div><em>待审核</em></button></SectionList></div><BottomNav active="profile" @navigate="navigate"/></section>

  <section v-else-if="view==='reading'" class="capture-page"><video ref="video" playsinline muted></video><canvas ref="canvas" hidden></canvas><div class="capture-shade"></div><header><button @click="leaveReading();view='home'">← 退出取景</button><div><strong>{{(state.readingSession?.status==='paused'?state.readingSession?.book_title:state.vision?.title)||'尚未识别书籍'}}</strong><span>{{state.readingSession?.status==='paused'?'阅读状态 · PAUSED':`识别状态 · ${state.vision?.status||'OFFLINE'}`}}</span></div><em>{{state.readingSession?.status==='paused'?'已暂停':'跟随中'}}</em></header><div class="focus-frame"><i></i><i></i><i></i><i></i></div><section class="capture-result"><strong>{{activePages}}</strong><p>{{state.vision?'保持书页完整地处于取景范围内':'请把书放入摄像头画面'}}</p></section><div class="capture-actions"><button @click="pauseReading">{{state.readingSession?.status==='paused'?'继续跟随阅读':'暂停并写批注'}}</button><button :disabled="!canMark" @click="markInspiration">此处有灵感</button><button @click="state.cameraStream?stopCamera():startCamera()">{{state.cameraStream?'关闭摄像头':'启动摄像头'}}</button><button @click="endReading">结束阅读</button></div><footer><span>{{state.cameraStatus}}</span><span>{{state.devices[0]?.name||'未绑定屏幕'}}</span></footer><BottomNav active="reading" @navigate="navigate"/></section>

  <section v-else-if="view==='enroll' && state.user?.role==='admin'" class="app-page enrollment-page"><header class="app-title"><div><span class="eyebrow">ADMIN / BOOK ENROLLMENT</span><h1>录入图书</h1></div><span>管理员</span></header><div class="enrollment-content"><section class="cover-stage" :class="{empty:!enrollment.preview}" @click="!enrollment.preview&&coverInput?.click()"><img v-if="enrollment.preview" :src="enrollment.preview" alt="待录入图书封面预览"><div v-else><strong>将封面放入画面</strong><p>保持正面、完整、光线均匀</p></div><input ref="coverInput" type="file" accept="image/*" capture="environment" hidden @change="selectCover"></section><form class="enrollment-form" @submit.prevent="uploadBook"><span class="eyebrow">REVIEW COVER</span><h2>{{enrollment.created?'录入完成':'确认书籍信息'}}</h2><template v-if="enrollment.created"><div class="enrollment-success"><span>BOOK ADDED</span><strong>《{{enrollment.created.title}}》</strong><small>{{enrollment.created.id}}</small></div><button class="button primary wide" type="button" @click="resetEnrollment">继续录入下一本</button></template><template v-else><p>拍摄后请核对封面与书名。确认后会写入云端书库，并进入后续封面识别。</p><button class="button outline wide" type="button" @click="coverInput?.click()">{{enrollment.preview?'重新拍摄或选择':'拍摄或选择封面'}}</button><label>书名<input v-model="enrollment.title" maxlength="160" placeholder="请输入或修正书名" required></label><p class="error">{{enrollment.error}}</p><button class="button primary wide" :disabled="enrollment.uploading||!enrollment.file">{{enrollment.uploading?'正在上传…':'确认并录入书库'}}</button></template></form></div><BottomNav active="enroll" @navigate="navigate"/></section>

  <section v-else-if="view==='annotation'" class="editor-page page"><header class="simple-header"><button @click="closeAnnotation">← 返回</button><span>{{statusText(state.activeComment?.status)}}</span></header><div class="editor-grid"><aside><span class="eyebrow">FROZEN CONTEXT</span><h1>{{state.activeComment?.book_title||'尚未识别书籍'}}</h1><strong>{{pages(state.activeComment)}}</strong><p>批注将保留当前冻结的跨页上下文。</p></aside><form @submit.prevent="submitComment"><header><div><span>01</span><h2>写下此刻的想法</h2></div><small>{{annotationText.length}} / 2000</small></header><textarea v-model="annotationText" maxlength="2000" placeholder="不必完整，先把这一刻留下来。" :disabled="state.activeComment?.status!=='draft'"></textarea><p class="error">{{formError}}</p><div v-if="state.activeComment?.status==='draft'" class="actions"><button class="button outline" type="button" @click="saveOnly">保存草稿</button><button class="button primary">提交审核</button></div><small>草稿只对你可见。提交后进入审核，审核通过才会出现在页边屏幕。</small></form></div></section>

  <section v-else-if="view==='review'" class="editor-page page"><header class="simple-header"><button @click="view='profile'">← 返回审核队列</button><span>待审核</span></header><div class="editor-grid"><aside><span class="eyebrow">READER SUBMISSION</span><h1>{{state.activeReview?.book_title}}</h1><strong>{{pages(state.activeReview)}}</strong><p>提交者：{{state.activeReview?.author_username}}</p></aside><article class="review-body"><h2>批注内容</h2><blockquote>{{state.activeReview?.body}}</blockquote><p class="error">{{formError}}</p><div class="actions"><button class="button outline" @click="review('rejected')">拒绝批注</button><button class="button primary" @click="review('approved')">批准并发布</button></div></article></div></section>

  <div v-if="bind.open" class="modal" @click.self="closeBind"><form class="bind-panel" @submit.prevent="bindDevice"><header><span>PAIR DEVICE</span><button type="button" @click="closeBind">关闭</button></header><template v-if="bind.scanning"><div class="qr-scanner"><video ref="qrVideo" playsinline muted></video><span class="qr-corner top-left"></span><span class="qr-corner top-right"></span><span class="qr-corner bottom-left"></span><span class="qr-corner bottom-right"></span></div><h2>扫描屏幕二维码</h2><p>{{bind.scanStatus}}</p><p class="error">{{bind.error}}</p><button class="button outline wide" type="button" @click="stopQrScan">改用机器码</button></template><template v-else><h2>绑定页边屏幕</h2><p>扫描屏幕待机页上的二维码，即可自动完成连接。</p><button class="button primary wide scan-button" type="button" @click="startQrScan"><span class="scan-icon" aria-hidden="true"></span>扫描二维码绑定</button><div class="bind-divider"><span>或输入机器码</span></div><label>机器码<input v-model="bind.code" placeholder="LM-DEMO-0001" required autofocus></label><p class="error">{{bind.error}}</p><button class="button outline wide">使用机器码绑定</button></template></form></div><Transition name="toast"><div v-if="toastText" class="toast">{{toastText}}</div></Transition>
</main>
</template>
